### ISSUE TITLE
[78.4] update text for 'need help' link in individual book record

### ISSUE THREAD

**Issue by bdolor** [BCcampus/opentextbooks#140]
**Is your feature request related to a problem? Please describe.**
I'm not clear on the reasoning behind removing the link. 

**Describe the solution you'd like**
Remove from the following list: 
![image](https://user-images.githubusercontent.com/2048170/53270640-22068d00-36a1-11e9-880f-a11702f4169f.png)

**Comment by paulagaube** [comment]
@brad @alex Can we hold off on this issue please? Kelsey and I have planned to meet today and tomorrow to discuss Open help/support issues and @josieg is joining us tomorrow to review. 

I think the link may be fine as is, since we can update the content on that help page. 

I believe the original concern was that "Contact helpdesk@bccampus.ca" as a bare email address was used on BCcampus.ca and maybe on some Open pages. Also, any links to CustomAnswers will need to change, as we plan on punting that service in the next month. (That will be before this new Open site launches.)

**Comment by bdolor** [comment]
sure...added a blocked label to indicate we're waiting on a decision to be made.

**Comment by alex-418** [comment]
@paulagaube any update on this one?

**Comment by paulagaube** [comment]
@alex-418 @bdolor 
Please DO NOT remove this help link on the individual book record, as the link will can the same. 
We have decided to update the content on the Help page instead, making this a NON-DEV task, and a different issue. https://open.bccampus.ca/help/

We will confirm this with Lauri in a meeting tomorrow morning. Then I believe we can close this issue.

**Comment by alex-418** [comment]
"Visit our help page"

**Comment by alex-418** [comment]
As per my comment, we capture the decision from a discussion with @paulagaube to keep the help link, but update the link text from 
`Visit our Help page for FAQ and helpdesk assistance`
to
 `Visit our help page`

@ehbeattie This link text is not version controlled, and lives in a settings file which is unique for each site... meaning there's no visible development work on Github for this. 

If you can confirm this decision, we'll have to add it as a launch day tasks for developers... or would you prefer I change this now on production? Please let me know what you'd prefer. 
![config](https://user-images.githubusercontent.com/17072191/54558577-548f6700-497b-11e9-95b8-8047c7202cd1.png)

**Comment by ehbeattie** [comment]
Let's deploy it now.

**Comment by alex-418** [comment]
Deployed. Can be verified by visiting a resource on production : 

![help](https://user-images.githubusercontent.com/17072191/54566363-e30ce400-498d-11e9-9e1e-a41dfafbf09e.png)

**Comment by alex-418** [comment]
Also updated cert (helga) to match prod

**Comment by ehbeattie** [comment]
Sweeeeet.

**Comment by paulagaube** [comment]
Thanks, @alex-418 ,  this is great.
